---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account_name }}
  labels: {{- include "labels" . | nindent 5 }}
---
# make the jwt token same name as the service_account_name
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service_account_name }}
  labels: {{- include "labels" . | nindent 5 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.service_account_name }}
type: kubernetes.io/service-account-token
---
# give required token review perms to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-{{ .Release.Name }}
  labels: {{- include "labels" . | nindent 5 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service_account_name }}
    namespace: {{ .Release.Namespace }}
