# Results from vault f1329e0f-d9c7-48d0-8b09-42df3c069579csi provider:
# 2024-01-23T19:40:53.095Z [INFO]  server: Finished unary gRPC call: grpc.method=/v1alpha1.CSIDriverProvider/Mount grpc.time=2.203817142s grpc.code=Unknown
#   err=
#   | error making mount request: couldn't read secret "shared": Error making API request.
#   |
#   | Namespace: client
#   | URL: GET ${VAULT_ADDR}/v1/kv2/data/shared
#   | Code: 403. Errors:
#   |
#   | * 1 error occurred:
#   | \t* permission denied
#   |
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ss-fail1
spec:
  provider: vault
  secretObjects:
    - secretName: csi-ss-fail1
      type: Opaque
      data:
      - objectName: shared
        key: sir
  parameters:
    roleName: {{ .Values.vault.role }}
    vaultSkipTLSVerify: "true"
    vaultAddress: {{ .Values.vault.address }}
    vaultNamespace: {{ .Values.vault.namespace }}
    vaultKubernetesMountPath: {{ .Values.vault.auth_path }}
    objects: |
      - objectName: shared
        secretPath: kv2/data/shared
        secretKey: sir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-csi-fail1
  labels: {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    labels: {{- include "selector_labels" . | nindent 6 }}
    matchLabels: {{- include "selector_labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "selector_labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.service_account_name }}
      containers:
        - name: main
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          resources: {{ .Values.resources | toYaml | nindent 11 }}
          volumeMounts:
          - name: secrets-store-inline
            mountPath: /mnt/csi
            readOnly: true
          command:
            - /bin/bash
            - -lc
            - |
              set -x
              ls -lh /mnt/csi
              res=$(cat /mnt/csi/regular)
              if [ "$res" != "sharesalot" ]; then
                echo failed to load csi secret
                exit 1
              fi
              echo csi success
              sleep 10000000
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ss-fail1

